language: java
jdk: openjdk11

env:
  global:
    - secure: $SONAR_TOKEN

addons:
  sonarcloud:
    organization: "darshanadsw"
    token:
      secure: $SONAR_TOKEN

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
