language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "darshanadsw"
    token: $SONAR_TOKEN

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
