spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://db:3306/dw_dev
    username: root
    password: root
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: dw_database_create.sql