spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dw_prod
    username: dw_prod_user
    password: dw
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false